### ISSUE TITLE
Missing parentheses in call to 'print'. Did you mean print(print query)?

### ISSUE THREAD

**Issue by shahbazwasti** [gsi-upm/sematch#21]
Hi,
I have installed and configured the library as you have instructed in the documentation. But I get this error:

>> from sematch.semantic.similarity import WordNetSimilarity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Shahbaz\AppData\Local\Continuum\anaconda3\lib\site-packages\sematch\semantic\similarity.py", line 25, in <module>
    from sematch.semantic.sparql import EntityFeatures, StatSPARQL
  File "C:\Users\Shahbaz\AppData\Local\Continuum\anaconda3\lib\site-packages\sematch\semantic\sparql.py", line 36
    print query
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print query)?
>>>

**Comment by shellshock1911** [comment]
This library is meant to be used with Python 2.7 only. `setup.py` indicates this in the notes at the bottom, however the author should have mentioned it in the README, or have it output an error message when a user tries to install it with Python 3.x.

**Comment by i-vishnuraj** [comment]
You can replace the **print query** in the **C:\Users\Shahbaz\AppData\Local\Continuum\anaconda3\lib\site-packages\sematch\semantic\sparql.py** with **print(query)**.

**Comment by balkian** [comment]
Closing this in favor of #31
