### ISSUE TITLE
ERROR: object of type 'map' has no len()

### ISSUE THREAD

**Issue by reverentSkin** [gsi-upm/sematch#25]
Hi, I'm a student that follows your research. 
I try to execute an example posted on GitHub page. 

`from sematch.semantic.graph import DBpediaDataTransform, Taxonomy
from sematch.semantic.similarity import ConceptSimilarity
import nltk
nltk.download('wordnet')
concept = ConceptSimilarity(Taxonomy(DBpediaDataTransform()),'models/dbpedia_type_ic.txt')
res1=concept.similarity('http://dbpedia.org/ontology/Actor','http://dbpedia.org/ontology/Film', 'path')
res2=concept.similarity('http://dbpedia.org/ontology/Actor','http://dbpedia.org/ontology/Film', 'wup')
print(res1,res2)`

And I have the following problem:

`File "/anaconda3/lib/python3.7/site-packages/sematch/semantic/graph.py", line 68, in __init__
    self._root = len(self._nodes) + 1      TypeError: object of type 'map' has no len()`

How can I do?

**Comment by sam-qordoba** [comment]
This seems like the library is made for python2 and you are using python 3. See pr #20. You could either use the fork in that PR, and hope it works, or use python2

**Comment by SmartMapple** [comment]
i met the same question at file graph.py.i want to use python2.7 version.don't know whether the question will be solved.

**Comment by dhimmel** [comment]
Python 2 reached end of life on January 1, 2020. Would love input from a repository maintainer if they intend to update this package to work with Python 3?

**Comment by balkian** [comment]
Closing this in favor of #31
