### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(query)?

### ISSUE THREAD

**Issue by rocana95** [gsi-upm/sematch#27]
the print query not work in python3 of course
---------------------------------------------------
class BaseSPARQL:
    def execution(self, query, show_query=False):
        if show_query:
            print query
        self._sparql.setQuery(query)
        results = self._sparql.query().convert()
        #print results
        return results["results"]["bindings"]

**Comment by balkian** [comment]
I'm closing this issue in favor of #31

**Comment by KseniiaKolesnichenko** [comment]
Hello! 
I can't understand how to solve this problem. Can you give me an advice?
![Снимок экрана (1889)](https://user-images.githubusercontent.com/73356081/124587483-53dab180-de60-11eb-997f-be3e18ac4ab7.png)
