### ISSUE TITLE
There was a problem install in Windows 10

### ISSUE THREAD

**Issue by liuqingzhuying** [gsi-upm/sematch#29]
E:\workfile\DrugBank>pip install sematch==1.0.4
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting sematch==1.0.4
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f4/1a/09377bdde1fcf4ede770c631e50199511a07921cf11dc66d3a83f2514277/sematch-1.0.4.tar.gz (9.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Te
mp\\pip-install-rea4rmch\\sematch\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-rea4rmch\\sematch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"
', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp
\pip-install-rea4rmch\sematch\pip-egg-info'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-rea4rmch\sematch\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-rea4rmch\sematch\setup.py", line 7, in <module>
        long_description = open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x97 in position 4162: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I know that's because python3 and python2 have different versions, causing “open('README.md').read(),” problems

**Comment by balkian** [comment]
Python 3 is not supported at the moment, but we are working on a new release with Py3 compatibility.

**Comment by balkian** [comment]
I am closing this in favor of #31
