### ISSUE TITLE
pls help install sematch on windows 10 computer

### ISSUE THREAD

**Issue by Sandy4321** [gsi-upm/sematch#4]
I try to install by pip install sematch
but there is very long error mesage

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\cde3>pip install sematch
Collecting sematch
Collecting SPARQLWrapper==1.5.2 (from sematch)
Requirement already satisfied: scikit-learn==0.17.1 in c:\users\cde3\anaconda3\lib\site-packages (from sematch)
Requirement already satisfied: networkx==1.11 in c:\users\cde3\anaconda3\lib\site-packages (from sematch)
Collecting scipy==0.13.2 (from sematch)
  Using cached scipy-0.13.2.zip
Requirement already satisfied: numpy==1.11.0 in c:\users\cde3\anaconda3\lib\site-packages (from sematch)
Collecting nltk==3.2 (from sematch)
Collecting rdflib==4.0.1 (from sematch)
Requirement already satisfied: decorator>=3.4.0 in c:\users\cde3\anaconda3\lib\site-packages (from networkx==1.11->sematch)
Requirement already satisfied: pyparsing in c:\users\cde3\anaconda3\lib\site-packages (from rdflib==4.0.1->sematch)
Collecting isodate (from rdflib==4.0.1->sematch)
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command c:\users\cde3\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\cde3\\AppData\\Local\\Temp\\pip-build-qrofeoyb\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\cde3\AppData\Local\Temp\tmpa_l6g0k4pip-wheel- --python-tag cp35:
  blas_opt_info:
  blas_mkl_info:
    libraries mkl,vml,guide not found in ['c:\\users\\cde3\\anaconda3\\lib', 'C:\\', 'c:\\users\\cde3\\anaconda3\\libs']
    NOT AVAILABLE

  openblas_info:
    libraries openblas not found in ['c:\\users\\cde3\\anaconda3\\lib', 'C:\\', 'c:\\users\\cde3\\anaconda3\\libs']
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
  c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:633: UserWarning: Specified path C:\projects\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
    warnings.warn('Specified path %s is invalid.' % d)
    libraries numpy-atlas not found in []
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries numpy-atlas not found in []
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries numpy-atlas not found in []
    NOT AVAILABLE

  atlas_blas_info:
    libraries numpy-atlas not found in []
    NOT AVAILABLE

  c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1640: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    warnings.warn(AtlasNotFoundError.__doc__)
  blas_info:
    libraries blas not found in ['c:\\users\\cde3\\anaconda3\\lib', 'C:\\', 'c:\\users\\cde3\\anaconda3\\libs']
    NOT AVAILABLE

  c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1649: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    warnings.warn(BlasNotFoundError.__doc__)
  blas_src_info:
    NOT AVAILABLE

  c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1652: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    warnings.warn(BlasSrcNotFoundError.__doc__)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\cde3\AppData\Local\Temp\pip-build-qrofeoyb\scipy\setup.py", line 230, in <module>
      setup_package()
    File "C:\Users\cde3\AppData\Local\Temp\pip-build-qrofeoyb\scipy\setup.py", line 227, in setup_package
      setup(**metadata)
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\cde3\AppData\Local\Temp\pip-build-qrofeoyb\scipy\setup.py", line 170, in configuration
      config.add_subpackage('scipy')
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1003, in add_subpackage
      caller_level = 2)
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 972, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 909, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 12, in configuration
      config.add_subpackage('integrate')
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1003, in add_subpackage
      caller_level = 2)
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 972, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 909, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\integrate\setup.py", line 12, in configuration
      blas_opt = get_info('blas_opt',notfound_action=2)
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 372, in get_info
      return cl().get_info(notfound_action)
    File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 566, in get_info
      raise self.notfounderror(self.notfounderror.__doc__)
  numpy.distutils.system_info.BlasNotFoundError:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
Failed to build scipy
Installing collected packages: isodate, rdflib, SPARQLWrapper, scipy, nltk, sematch
  Found existing installation: scipy 0.18.1
    Uninstalling scipy-0.18.1:
      Successfully uninstalled scipy-0.18.1
  Running setup.py install for scipy ... error
    Complete output from command c:\users\cde3\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\cde3\\AppData\\Local\\Temp\\pip-build-qrofeoyb\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\cde3\AppData\Local\Temp\pip-ql2jonbq-record\install-record.txt --single-version-externally-managed --compile:
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['c:\\users\\cde3\\anaconda3\\lib', 'C:\\', 'c:\\users\\cde3\\anaconda3\\libs']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['c:\\users\\cde3\\anaconda3\\lib', 'C:\\', 'c:\\users\\cde3\\anaconda3\\libs']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
    c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:633: UserWarning: Specified path C:\projects\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
      libraries numpy-atlas not found in []
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries numpy-atlas not found in []
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries numpy-atlas not found in []
      NOT AVAILABLE

    atlas_blas_info:
      libraries numpy-atlas not found in []
      NOT AVAILABLE

    c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1640: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    blas_info:
      libraries blas not found in ['c:\\users\\cde3\\anaconda3\\lib', 'C:\\', 'c:\\users\\cde3\\anaconda3\\libs']
      NOT AVAILABLE

    c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1649: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      warnings.warn(BlasNotFoundError.__doc__)
    blas_src_info:
      NOT AVAILABLE

    c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1652: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      warnings.warn(BlasSrcNotFoundError.__doc__)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\cde3\AppData\Local\Temp\pip-build-qrofeoyb\scipy\setup.py", line 230, in <module>
        setup_package()
      File "C:\Users\cde3\AppData\Local\Temp\pip-build-qrofeoyb\scipy\setup.py", line 227, in setup_package
        setup(**metadata)
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\cde3\AppData\Local\Temp\pip-build-qrofeoyb\scipy\setup.py", line 170, in configuration
        config.add_subpackage('scipy')
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1003, in add_subpackage
        caller_level = 2)
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 972, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 909, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 12, in configuration
        config.add_subpackage('integrate')
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1003, in add_subpackage
        caller_level = 2)
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 972, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 909, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\integrate\setup.py", line 12, in configuration
        blas_opt = get_info('blas_opt',notfound_action=2)
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 372, in get_info
        return cl().get_info(notfound_action)
      File "c:\users\cde3\anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 566, in get_info
        raise self.notfounderror(self.notfounderror.__doc__)
    numpy.distutils.system_info.BlasNotFoundError:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.

    ----------------------------------------
  Rolling back uninstall of scipy
Command "c:\users\cde3\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\cde3\\AppData\\Local\\Temp\\pip-build-qrofeoyb\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\cde3\AppData\Local\Temp\pip-ql2jonbq-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\cde3\AppData\Local\Temp\pip-build-qrofeoyb\scipy\

C:\Users\cde3>

**Comment by hopple** [comment]
We have updated the installation. You may try again.
